export const SCREEN_DECKS = "DecksScreen"
export const SCREEN_DECK_DETAILS_SCREEN = "DeckDetailsScreen"
export const SCREEN_NEW_DECK = "NEW DECK"
export const DECKS = "DECKS"
export const ADD_CARD_SCREEN = "ADD_CARD_SCREEN"
export const QUIZ_SCREEN = "QUIZ_SCREEN"